### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by lupa18** [miguelmarco/pyzcto#1]
I follow your advices, so created a virtualenv, and installed dependencies:
```
virtualenv -p python3 pyzcto
source bin/activate
pip install simplejson pyqt5 requests qrcode

```
and then run the software. I changed password in Zcash tab, but it says "Not connected to daemon..."

(Zcashd is running)

**Comment by miguelmarco** [comment]
Check that the username and password that you have in pyzcto match the ones you have in your `zcash.conf` file. 

Also check that the port set in pyzcto matches the one that your zcash daemon is listening (8232 by default).

Finally, check that there is no firewall blocking that port.

Does the cli interface work for you?

**Comment by lupa18** [comment]
I double checked all params and try this command: 
`curl --user username --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getbalance", "params": ["*", 6] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/`

and discovered I had an error in the password. 
Sorry and thanks !

**Comment by mmitech** [comment]
I have the same issue, double checked everything and still no luck!

**Comment by miguelmarco** [comment]
Can you use the command line interface?

**Comment by mmitech** [comment]
> Can you use the command line interface?

Not sure what do you mean by that, but this is what I did:
- Install all dependencies.
- Set Zcash config file and start it
- run the pyzcto by running `python3 pyzcto.py` 

Result: the pyzcto window open up with the message on the bottom left side "Not connected to daemon, Please check settings"

 the Zcash Tab shows the correct credentials.

**Comment by miguelmarco** [comment]
What happens if you try to run `zcash-cli help` ?

**Comment by mmitech** [comment]
I get the supported RPC commands.

**Comment by miguelmarco** [comment]
Hmm, that's weird. Try what lupa18 did.

**Comment by mmitech** [comment]
yes, I tried that, I get a successful response with balance 0.

**Comment by miguelmarco** [comment]
That is really weird.

Can you use some packet capture tool (like wireshark) to see what is going on in your network when pyzcto tries to connect?

**Comment by mmitech** [comment]
OK, that is something I can try yes. Will update you on this.
